/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi.laundry;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irsan Achmad
 */
public class Transaksi extends javax.swing.JFrame implements Runnable{
    
    
    int hour,second,minute;
    
    public void clearForm(){
        nomor.setText(null);
        nama.setText(null);
        jam.setText(null);
        parfum.setSelectedIndex(0);
        berat.setText(null);
        jumlah.setText(null);
        harga.setText(null);
    }
    
    public void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor Antrian");
        model.addColumn("Nama");
        model.addColumn("Tanggal");
        model.addColumn("Jam");
        model.addColumn("Parfum");
        model.addColumn("Berat");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
        
        String cari = btncari.getText();
        
        try {
            int no = 1;
            String sql = "SELECT * FROM tb_transaksi WHERE Nama LIKE'%"+cari+"%'";
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/laundry", "root", "");
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {                
                model.addRow(new Object[] {
                    res.getString(1), res.getString(2), res.getString(3), res.getString(4),
                    res.getString(5), res.getString(6), res.getString(7), res.getString(8)
                });
                TabelTransaksi.setModel(model);
            }
            
        } catch (Exception e) {
            System.out.println("ERROR : "+ e.getMessage());
        }
    }

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        tampilkan_data();
        clearForm();
        Image icon = Toolkit.getDefaultToolkit().getImage("src/Image/LaundryLogo.png");
        setIconImage(icon);
        //creating thread
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomor = new javax.swing.JTextField();
        parfum = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        berat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jam = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btncari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Laundry");
        setPreferredSize(new java.awt.Dimension(950, 579));
        setResizable(false);
        getContentPane().setLayout(null);

        nomor.setBackground(new java.awt.Color(245, 245, 245));
        nomor.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        nomor.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nomor);
        nomor.setBounds(209, 115, 210, 30);

        parfum.setBackground(new java.awt.Color(245, 245, 245));
        parfum.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        parfum.setForeground(new java.awt.Color(0, 0, 0));
        parfum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mawar", "Sakura", "Snapy", "Downy Mistiq", "Downy Passion", "Ocean Fresh", "Lavender ", "Lily", "Aqua Fresh", "Phonix" }));
        getContentPane().add(parfum);
        parfum.setBounds(209, 278, 210, 30);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Total Harga");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(35, 476, 80, 30);

        jPanel1.setBackground(new java.awt.Color(39, 73, 109));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM TRANSAKSI LAUNDRY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 20, 330, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 70);

        jPanel2.setBackground(new java.awt.Color(0, 168, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        berat.setBackground(new java.awt.Color(245, 245, 245));
        berat.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        berat.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jam Masuk");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nama Pelanggan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tanggal Masuk");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nomor Antrian");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 40));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jenis Parfum");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Berat Pakaian");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jumlah Pakaian");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        nama.setBackground(new java.awt.Color(245, 245, 245));
        nama.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, 30));

        tanggal.setBackground(new java.awt.Color(245, 245, 245));
        tanggal.setDateFormatString("dd-MM-yyyy");
        tanggal.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, 30));

        jButton2.setBackground(new java.awt.Color(20, 40, 80));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gtk-save-as.png"))); // NOI18N
        jButton2.setText("TAMBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, 30));

        jam.setBackground(new java.awt.Color(245, 245, 245));
        jam.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jam.setForeground(new java.awt.Color(0, 0, 0));
        jam.setText("00:00:00");
        jPanel2.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, 30));

        jButton4.setBackground(new java.awt.Color(20, 40, 80));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gtk-edit.png"))); // NOI18N
        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 30));

        jButton5.setBackground(new java.awt.Color(20, 40, 80));
        jButton5.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/document_delete.png"))); // NOI18N
        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, 30));

        jButton6.setBackground(new java.awt.Color(20, 40, 80));
        jButton6.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/application-exit.png"))); // NOI18N
        jButton6.setText("KEMBALI");
        jButton6.setPreferredSize(new java.awt.Dimension(95, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 120, 30));

        TabelTransaksi.setBackground(new java.awt.Color(245, 245, 245));
        TabelTransaksi.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        TabelTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama", "Tanggal", "Jam", "Parfum", "Berat", "Jumlah", "Harga"
            }
        ));
        TabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelTransaksi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 280));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cari :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 30));

        btncari.setBackground(new java.awt.Color(245, 245, 245));
        btncari.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        btncari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncariKeyReleased(evt);
            }
        });
        jPanel2.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 210, 30));

        jButton3.setBackground(new java.awt.Color(20, 40, 80));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton3.setText("REFRESH");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, 30));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Kilogram");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 30));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Pakaian");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 60, 30));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rp :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 30));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Rupiah");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, 30));

        jButton1.setBackground(new java.awt.Color(20, 40, 80));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 210, 30));

        jumlah.setBackground(new java.awt.Color(245, 245, 245));
        jumlah.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jumlah.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 30));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 2, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("*Harga Perkilo Rp 8.000");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 140, 20));

        harga.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(0, 0, 0));
        harga.setText("0");
        jPanel2.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 940, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int Jumlah,Harga;
        Double Berat;
        Berat = Double.parseDouble(String.valueOf(berat.getText()));
        Jumlah = Integer.parseInt(String.valueOf(jumlah.getText()));
        Harga = (int)(Berat*8000);
        String HargaF = String.format("%,d", Harga);
        harga.setText(HargaF);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String tgl = ((JTextField)tanggal.getDateEditor().getUiComponent()).getText();
        
        
        try {
            String sql = "INSERT INTO tb_transaksi VALUES ('"+nomor.getText()+"','"+nama.getText()+
            "','"+tgl+"','"+jam.getText()+"','"+parfum.getSelectedItem()+"','"+berat.getText()
            +"','"+jumlah.getText()+"','"+harga.getText()+"')";
            
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/laundry", "root", "");
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Simpan Data Gagal");
        }
        
        tampilkan_data();
        clearForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)TabelTransaksi.getModel();
        
        String tblnomor = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 0).toString();
        String tblnama = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 1).toString();
        String tblparfum = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 4).toString();
        String tblberat = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 5).toString();
        String tbljumlah = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 6).toString();
        String tblharga = tblmodel.getValueAt(TabelTransaksi.getSelectedRow(), 7).toString();
        
        nomor.setText(tblnomor);
        nama.setText(tblnama);
        parfum.setSelectedItem(tblparfum);
        berat.setText(tblberat);
        jumlah.setText(tbljumlah);
        harga.setText(tblharga);
    }//GEN-LAST:event_TabelTransaksiMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE tb_transaksi SET Nama=?, Parfum=?, Berat=?, Jumlah=?, Harga=? WHERE `NomorAntrian`=?";
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/laundry", "root", "");
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, nama.getText());
            pst.setString(2, parfum.getSelectedItem().toString());
            pst.setString(3, berat.getText());
            pst.setString(4, jumlah.getText());
            pst.setString(5, harga.getText());
            pst.setString(6, nomor.getText());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
            } else {
                JOptionPane.showMessageDialog(null, "Edit Data Gagal");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


        tampilkan_data();
        clearForm();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Mendapatkan nomor baris yang dipilih oleh pengguna
        int selectedRow = TabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus baris ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/laundry", "root", "");
                    Statement stmt = con.createStatement();
                    DefaultTableModel model = (DefaultTableModel) TabelTransaksi.getModel();
                    int selectedRowIndex = TabelTransaksi.getSelectedRow();
                    String nomorAntrian = model.getValueAt(selectedRowIndex, 0).toString();
                    String deleteQuery = "DELETE FROM tb_transaksi WHERE NomorAntrian='" + nomorAntrian + "'";
                    stmt.executeUpdate(deleteQuery);
                    model.removeRow(selectedRowIndex);
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus baris");
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelTransaksi.getModel();
        model.setRowCount(0);
        tampilkan_data();
    }//GEN-LAST:event_jButton3MouseClicked

    private void btncariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncariKeyReleased
        // TODO add your handling code here:
        tampilkan_data();
    }//GEN-LAST:event_btncariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JTextField berat;
    private javax.swing.JTextField btncari;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jam;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomor;
    private javax.swing.JComboBox<String> parfum;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) { 
            //get current hour minute second
            Calendar cal = Calendar.getInstance();
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss");
            Date dat = cal.getTime();
            String time24 = sdf24.format(dat);
            
            //set to textfield
            jam.setText(time24);
        }
    }
}
